// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olivia.Web.Models.Data;

namespace Olivia.Web.Migrations
{
    [DbContext(typeof(OliviaContext))]
    partial class OliviaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Olivia.Web.Models.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .IsUnicode(false);

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .HasName("fk_post_user");

                    b.ToTable("post","sheeminc_olivia");
                });

            modelBuilder.Entity("Olivia.Web.Models.Data.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .IsUnicode(false);

                    b.Property<byte>("EmailConfirmed")
                        .HasColumnName("email_confirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .IsUnicode(false);

                    b.HasKey("Username");

                    b.ToTable("user","sheeminc_olivia");
                });

            modelBuilder.Entity("Olivia.Web.Models.Data.Post", b =>
                {
                    b.HasOne("Olivia.Web.Models.Data.User", "UsernameNavigation")
                        .WithMany("Post")
                        .HasForeignKey("Username")
                        .HasConstraintName("fk_post_user")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
